name: Mobile Test Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium server
        run: appium &

      - name: Run UI Tests
        uses: faruktoptas/android-github-actions-emulator

      - name: Executar testes com Robot Framework e Appium
        run: |
          robot -d ./logs tests

      - name: Logs e Relatórios
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ./logs
          retention-days: 30
