name: Mobile Test Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium server
        run: appium &

      - name: Change permissions of gradlew
        run: chmod +x $GITHUB_WORKSPACE/gradlew

      - name: Run tests with emulator.wtf
        uses: emulator-wtf/run-tests@v0
        with:
          api-token: AgAAX2TBDGeGMroh477kulG8qUHbUPJeTPiC8ehdKU8UCvhB6bI12ftyn499GEcca0rxnLsvXubXQtcw+sLqmVcC8XxWh7qxOmS/gng58UW5d/dEKT8exioSe0zAqLem+B49Rf2L36IXHW0Z/WFVCrPC7PNp43Wa+xv38DlgzyeRyFqrLX5H7jQ1dJ4QkAMisvOM
          app: path/to/your/app-debug.apk
          test: path/to/your/test.apk
          outputs-dir: build/test-results
          # Add other configuration options as needed

      - name: Executar testes com Robot Framework e Appium
        run: |
          robot -d ./logs tests

      - name: Logs e Relatórios
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ./logs
          retention-days: 30
